name: evolutionaryscale
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  - python==3.10
  - pytorch::pytorch==2.1.2
  # - pytorch-cuda==12.1
  # - nvidia::cuda-toolkit==12.1
  - torchvision
  - torchtext
  - transformers
  - ipython
  - einops
  - biotite
  - msgpack-numpy
  - biopython
  - scikit-learn
  - cloudpathlib
  - attrs
  - numpy<2
