name: ProteinAnnotation
description: "Predict protein function annotations with ESM3"
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  input_pdb:
    description: "Path to input pdb"
    optional: false
  model_parameters:
    description: "Path to model parameters"
    optional: false
storageCapacity: 1200
tags:
  Name: "ProteinAnnotation"
