name: MMseqs2
description: "MMseqs2: ultra fast and sensitive search and clustering suite"
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  fasta_path:
    description: "FASTA file containing query sequence."
    optional: false
  database_name:
    description: "MMSeqs database name found at https://github.com/soedinglab/mmseqs2/wiki#downloading-databases."
    optional: true
storageCapacity: 1200
tags:
  Name: "MMseqs2"
accelerators: GPU
