# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

project:
  name: aho-drug-discovery-workflows
  package_lambda: false
  s3_bucket: ddw-deployment-588738610715-uw2
  regions:
    - us-west-2
  parameters:
    ApplicationName: "aho-ddw-taskcat"
    S3BucketName: "ddw-deployment-588738610715-uw2"
    WaitForCodeBuild: "Y"
    DeployContainer: "N"
    DeployWorkflow: "Y"
    DeployData: "N"
tests:
  default:
    template: build/cloudformation/packaged.yaml
