name: RFDiffusion
description: "Generate 3D protein structures"
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  input_pdb: 
    description: "Input PDB file for scaffolding."
    optional: false
  model_params: 
    description: "S3 path of rfdiffusion model files"
    optional: false
  container_image: 
    description: "Container image"
    optional: false
storageCapacity: 1200
tags:
  Name: "RFDiffusion"