name: RFDiffusion
description: "Generate 3D protein structures"
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  input_pdb: 
    description: "Input PDB file for scaffolding."
    optional: false
storageCapacity: 1200
tags:
  Name: "RFDiffusion"