name: Predict Protein Complexes
description: "Predict the structure of biomolecular complexes"
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  query:
    description: "Path to S3 object or folder containing query sequences."
    optional: false
  use_msa:
    description: "Generate and provide MSA as input to structure prediction"
    optional: true
  use_templates:
    description: "Find and provide templates as input to structure prediction"
    optional: true
  constraints_path:
    description: "Optional path to .csv file containing constraints information"
    optional: true    
  filter:
    description: "Filter the MSA by pre-defined align_eval, qsc, max_accept."
    optional: true
  expand_eval:
    description: "e-val threshold for 'expandaln'."
    optional: true
  align_eval:
    description: "e-val threshold for 'align'."
    optional: true
  diff:
    description: "filterresult - Keep at least this many seqs in each MSA block."
    optional: true
  qsc:
    description: "filterresult - reduce diversity of output MSAs using min score thresh."
    optional: true
  max_accept:
    description: "align - Maximum accepted alignments before alignment calculation for a query is stopped."
    optional: true
  pairing_strategy:
    description: "pairaln - Pairing strategy. 0: pair maximal per species, 1: pair only if all chains are covered per species [0]"
    optional: true
  db_load_mode:
    description: "Database preload mode 0: auto, 1: fread, 2: mmap, 3: mmap+touch"
    optional: true
  unpack:
    description: "Unpack results to loose files (1) or keep MMseqs2 databases (0)."
    optional: true
  gpu_server:
    description: "Whether to use GPU server (1) or not (0). Only needed for processing a large number of inputs."
    optional: true
  recycle_msa_subsample:
    description: "Number of msa subsample recycles. Defaults to 0."
    optional: true
  num_trunk_recycles:
    description: "Number of trunk recycles. Defaults to 3."
    optional: true
  num_diffn_timesteps:
    description: "Number of diffusion steps. Defaults to 200."
    optional: true
  num_diffn_samples:
    description: "Number of diffusion samples. Defaults to 5."
    optional: true
  num_trunk_samples:
    description: "Number of trunk samples. Defaults to 1."
    optional: true
  seed:
    description: "Seed value. Defaults to none."
    optional: true
  uniref30_db_path:
    description: "Path to S3 folder containing indexed uniref (e.g. uniref30_2302_db) data."
    optional: true
  envdb_db_path:
    description: "Path to S3 folder containing indexed ennvironment (e.g. colabfold_envdb_202108_db) data."
    optional: true
  pdb100_db_path:
    description: "Path to S3 folder containing indexed pdb (e.g. pdb100_230517_db) data."
    optional: true
  pdb_snapshot_path:
    description: "Optional path to folder containing snapshot structures from rcsb pdb"
    optional: true    
  chai1_parameters:
    description: "Path to folder containiner Chai-1 model parameters."
    optional: true    
storageCapacity: 1200
tags:
  Name: "Protein-Complex"
accelerators: GPU
