name: Boltz1
description: "State-of-the-art open-source model to predict biomolecular structures containing combinations of proteins, RNA, DNA, and other molecules."
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  input_path:
    description: "Path to fasta or yaml input file."
    optional: false
  boltz1_parameters:
    description: "Path to folder containiner Boltz-1 model parameters."
    optional: true    
storageCapacity: 1200
tags:
  Name: "Boltz1"
accelerators: GPU
