name: Nanobody Design
description: "Generate nanobodies to a target of interest."
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  target_pdb: 
    description: "S3 URI of target PDB file."
    optional: false
  scaffold_pdb:
    description: "S3 URI of scaffold PDB file."
    optional: false
  hotspot_residues:
    description: "RFDiffusion hotspot residues indices. See https://github.com/RosettaCommons/RFdiffusion/tree/main?tab=readme-ov-file#binder-design for more information."
    optional: false
  num_str_designs_per_target:
    description: "(Optional) Number of protein backbone designs per input target."
    optional: true
  num_seq_designs_per_str:
    description: "(Optional) Number of protein sequence designs per backbone design."
    optional: true
  num_parallel_workflows:
    description: "(Optional) Number of generation workflows to run in parallel."
    optional: true
  rfdiffusion_model_parameters:
    description: "(Optional) S3 URI of RFDIffusion model parameter file"
    optional: true
  proteinmpnn_model_parameters:
    description: "(Optional) S3 URI of ProteinMPNN model parameter file"
    optional: true        
  esmfold_model_parameters:
    description: "(Optional) S3 URI of ESMFold model parameter file"
    optional: true            
storageCapacity: 1200
tags:
  Name: "Nanobody"