name: RFDiffusion
description: "Generate 3D protein structures"
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  input_pdb: 
    description: "S3 URI of input PDB file."
    optional: false
  config_file:
    description: "S3 URI of hydra config file"
    optional: false
storageCapacity: 1200
tags:
  Name: "RFDiffusion"