name: TemStaPro
description: "Predict protein thermostability using sequence representations from a protein language model. From Institute of Biotechnology, Life Sciences Center, Vilnius University."
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  fasta_path:
    description: "Input file in FASTA format."
    optional: false
  window_size_predictions:
    description: "set the window size for average smoothing of per residue predictions for plotting. Defaults to 81."
    optional: true    
  portion_size:
    description: "Maximum size of input sequence divisions. Set to 0 for no division. Defaults to 1000."
    optional: true      
storageCapacity: 1200
tags:
  Name: "TemStaPro"
accelerators: GPU
