name: NIMAgentBlueprint
description: "MolMIM => Alphafold2 => Diffdock"
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  smi_input_path: 
    description: "Input SMILES."
    optional: false
  fasta_path: 
    description: "Input file in FASTA format."
    optional: false
  num_molecules:
    description: "Number of molecules to generate by MolMIM."
    optional: false
  num_poses:
    description: "Number of docking poses."
    optional: false
  max_retries:
    description: "Max number of retries of Nextflow processes."
    optional: false
storageCapacity: 4800
tags:
  Name: "NAB"