name: Nextflow Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Run Nextflow Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Nextflow Linter
        run: |
          docker run -v ${{ github.workspace }}/assets/workflows:/data \
          public.ecr.aws/aws-genomics/linter-rules-for-nextflow
