name: Lint Nextflow Pipelines

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Nextflow pipelines
        run: |
          docker run --rm --platform linux/amd64 -v ${{ github.workspace }}:/data public.ecr.aws/aws-genomics/linter-rules-for-nextflow:v0.1

          echo "$output"
    
          # Extract P1 violations and count them
          P1_count=$(echo "$output" | grep -c 'P=1')

          # Colorize output for better visibility
          echo "$output" | sed 's/P=1/\x1b[31mP=1\x1b[0m/g' | sed 's/P=2/\x1b[33mP=2\x1b[0m/g' | sed 's/P=3/\x1b[32mP=3\x1b[0m/g'

          # Fail if there are any P1 violations
          if [ "$P1_count" -gt 0 ]; then
            echo "❌ Lint failed due to $P1_count critical violation(s)."
            exit 1
          else
            echo "✅ No critical violations found."
          fi
