name: Lint Nextflow Pipelines

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build Docker Image
        run: |
          docker build -t nextflow-linter https://github.com/awslabs/linter-rules-for-nextflow.git#main

      - name: Lint Nextflow pipelines
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace nextflow-linter \
          java -Dorg.slf4j.simpleLogger.defaultLogLevel=error \
          -classpath /linter-rules/build/libs/linter-rules-0.1.jar:/CodeNarc-3.3.0-all.jar:/slf4j-api-1.7.36.jar:/slf4j-simple-1.7.36.jar \
          org.codenarc.CodeNarc \
          -report=text:stdout \
          -rulesetfiles=/linter-rules/rulesets/healthomics.xml \
          -includes=**/*.nf
