name: NextFlow Lint

on: [pull_request, workflow_dispatch]

jobs:
  nf-core-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # Nextflow Linting
    - name: Install Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
        mv nextflow /usr/local/bin/

    - name: Lint Nextflow pipelines
      run: |
        find . -type f \( -name 'nextflow.config' -o -name 'main.nf' \) -exec nextflow lint {} \;
