name: NextFlow Lint

on: [pull_request, workflow_dispatch]

jobs:
  nf-core-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # Nextflow Linting
    - name: Install Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
        mv nextflow /usr/local/bin/

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install nf-core/tools
      run: |
        pip install nf-core

    - name: Lint Nextflow pipelines
      run: |
        cd workflows
        for wf in ./workflows/*/
        do
          cd "$wf"
          nf-core lint .
          cd - > /dev/null
        done
